### ISSUE TITLE
red flashes with user firmware

### ISSUE THREAD

**Issue by kennethlimcp** [spark/spark-server#18]
Seems like besides `tinker app`, running other firmware results in SOS panic red flashes. 

Looks like 2 flash - Non-maskable interrupt fault

Flashing via OTA or DFU resulted in the same behavior.

I will be loading the code in via DFU, test on the LC and switch to Spark Cloud and see what's the result like.

**Comment by emilyrose** [comment]
I haven't been able to reproduce this issue with current versions of firmware and spark-server. If anyone is still having trouble with this please feel free to reopen the issue.
