### ISSUE TITLE
Unable to Call function or variable via api.

### ISSUE THREAD

**Issue by seanlim1** [spark/spark-server#41]
I dont quite understand what's going on here. My curl/api request is returning:
'Not Found' instead of json replies.

I used the following command in my cmd:
curl http://[LOCAL IP:PORT]/v1/device/[SPARK ID]/[FUNCTION]?access_token=[TOKEN]

Over on the server end, it's getting :
GET /v1/device/[SPARK ID]/[FUNCTION]?access_token=[TOKEN] HTTP/1.1" 404 9 "-" "curl/7.30.0"

Hope someone can enlighten me on what's going on. Thanks in advance!

**Comment by dmiddlecamp** [comment]
I think you want `/v1/devices/` instead of `/v1/device/`, no?

**Comment by seanlim1** [comment]
oh my goodness! Yes it is. Apologies for something soo trivial.

**Comment by dmiddlecamp** [comment]
no worries!  Glad we could help! :)
