### ISSUE TITLE
OTA firmware update for Photons not working

### ISSUE THREAD

**Issue by chuank** [spark/spark-server#54]
Photons are able to connect to local cloud, but OTA updates are not working.

https://community.particle.io/t/private-event-seems-didnt-get-to-work-in-local-cloud/9415/13

**Comment by tslater** [comment]
+1
It looks like these are working for the spark...
https://github.com/spark/spark-server/issues/25

**Comment by chuank** [comment]
If you're referring to the Cores, yes OTAs are working fine. But not for the Photons.

**Comment by tslater** [comment]
That has been my experience. It says success but then the code isn't flashed. I wonder if anyone here can hint on what might need to be done. I'd like to work on it if there isn't already something in progress.

**Comment by affinity-matrix** [comment]
I believe this is due to the difference in the way system firmware and user apps are saved on the devices themselves. @tslater if you were up for the task of working on this, I will be more than happy to help facilitate you in any way I can. Feel free to ping me if you have specific questions!

**Comment by tslater** [comment]
If I have time, I'm definitely wanting to poke around. I remember seeing
some of the code on the server for the flash, I haven't looked around much
on the firmware repo yet so any direction on how the files are stored or
how everything works would be great to get a head start.
ᐧ

**Comment by javier-rodas** [comment]
Hi @emilyrose and @kennethlimcp   It seems that this OTA firmware upgrade BUG with the Photon doesn't have much priority for you, as we reported it and requested a solution back in 12-th July, or even earlier by @kennethlimcp  :cry: . #45 

For me, and imagine that for many others, this BUG is quite critical and make the local spark-server nearly unusable nowadays with the Photon, don't you agree?.

So what I could only do is to offer me for collaboration and try to fix it. I will be available for testing it deeply with the Photon starting from the next week, and from the **latest "stable" 0.4.4 Photon firmware** starting point, recently released, if you agree.

Could I expect some collaboration from your side to try to fix it with my (and others) testings?.

Thanks in advance for your support.

**Comment by tslater** [comment]
I agree with you @javier-rodas . I know they're busy with the electron and such, but I hope the open-sourceness spirit stays alive. Any word on this? I've been patiently waiting too! It seems like development on the local cloud is very, very dead. Can we at least get an idea of what the situation is?

**Comment by kennethlimcp** [comment]
I'm sure this will be worked on but definitely not a high priority with so many other stuff on going. Local :cloud: was announced for the Spark core during kickstarter and that setup is working. 

@zsup might be able to give a high level overview here

**Comment by chuank** [comment]
@kennethlimcp, this issue is about the non-availability of OTAs for _Photons_ on `spark-server`.

I think everyone here is aware that OTAs work on Cores, which is fine – but with Particle stopping production on Cores and moving to Photons, I agree with @tslater and @javier-rodas that there should be at least some attention on `spark-server` to fix the bugs – #54, #55 and to a lesser extent #53 and #56.

On the bright side, @emilyrose did mention in this [discussion thread](https://community.particle.io/t/local-cloud-spark-server-various-issues/14346/7) that work might be done on `spark-server` soon.

An official response with the likes of "Yes, we'll definitely get this out by Christmas", or a clear "No, we do not intend to support `spark-server` forever" will be good.

This will help those of us evaluating solutions to either wait for better local cloud support, or start crunching and pooling our resources right now to explore alternatives.

p.s. I too will be happy to participate in testing!

**Comment by dmiddlecamp** [comment]
Hi all!

  Sorry about the lack of feedback on this issue!  It's definitely a priority, and I'll / we'll take a stab at testing and porting this next week. :)

Thanks
David

**Comment by tslater** [comment]
@dmiddlecamp That's awesome. I really appreciate that.

**Comment by dmiddlecamp** [comment]
Fixed with new release 0.1.6, sorry about the delay on this one!

**Comment by javier-rodas** [comment]
@dmiddlecamp Thank you very much for the quick response since your last comment, 6 days ago!!... but where can we find that 0.1.6 release?  I do not see any new commits or releases for this project https://github.com/spark/spark-server

**Comment by dmiddlecamp** [comment]
Hi @javier-rodas,

  Good question, the update is in the spark-protocol project, try deleting that module and reinstalling:

```
# something like... 
cd local-server/js
rm -rf node_modules/spark-protocol
npm install

# there is probably a more fancy syntax (but the above method is easier to confirm :) )
npm update / upgrade
```

**Comment by chuank** [comment]
@dmiddlecamp Thanks for this update. Tested OTA and it's working. ~~`npm update` works re:updating of the spark-protocol files.~~ the older spark-protocol folder must be deleted and reinstalled again using `npm install` in order to work.

**Comment by peqc1300** [comment]
I have a question. Is this OTA a firmware that is built int he local server or does it extract it from the cloud? I don't see where we can OT  the firmware that we want (which would include modifications to running code).
