### ISSUE TITLE
SparkServer in production

### ISSUE THREAD

**Issue by zachcr-ws** [spark/spark-server#64]
Hi, i want to config a spark-server in my server cluster, there will be a private net to launch this server.Use load balance to open 8080 port for this server.
But i can not use Photon to connect the cloud. Are there anything i need to know about the load Balance setting? Except 8080 port, do i need open other port for their connection?

**Comment by kennethlimcp** [comment]
You need port 5683 TCP for COAP protocol

**Comment by zachcr-ws** [comment]
OKay, thanks. I am trying

**Comment by zachcr-ws** [comment]
Thank you very much
