### ISSUE TITLE
Subscribe does not work

### ISSUE THREAD

**Issue by robin13** [spark/spark-server#71]
Photon with 0.5.1 firmware does not subscribe.

The photon becomes unresponsive (steady (**not breathing**) cyan mode light) and no further code is executed.

I have tested the same code against the particle cloud and it works there.

**Comment by straccio** [comment]
Ha e you tried this ?
https://github.com/spark/spark-protocol/pull/12/commits/2a341ceafa448167beef0e94e6199cdd3d39e394

**Comment by technobly** [comment]
Please see resolution here https://github.com/spark/firmware/issues/1021
