### ISSUE TITLE
What are the features that are present only on the Particle cloud ?

### ISSUE THREAD

**Issue by bilics** [spark/spark-server#77]
Hi! I hope this is right place to ask :)

I understand this project provides a subset of the features of the actual Particle cloud - is this correct ?

What are the features that are missing then ?

Thanks!

**Comment by dmiddlecamp** [comment]
Hi @bilics,

  Good question!  Some of that is answered here, but it's increasingly out of date:

https://github.com/spark/spark-server#what-api-features-are-missing

We've added lots and lots of features and improvements to the enterprise Particle cloud, not to mention 24/7 monitoring and alerting and maintenance.  Feel free to ping the sales team here if you're curious about running a private cloud versus using the enterprise cloud - https://www.particle.io/sales

Thanks,
David

**Comment by bilics** [comment]
Thanks @dmiddlecamp! I will drop them a note,

best!
